import type Anthropic from "@anthropic-ai/sdk";
import { zodOutputFormat } from "@anthropic-ai/sdk/helpers/zod";
import { EXTRACTION_MODEL, getAnthropicClient } from "@/lib/anthropic";
import {
  extractionPayloadSchema,
  type ExtractionPayload,
  type LcaExtraction,
} from "@/types/lca";
import { extractPdfText } from "./pdf";

/**
 * Claude-based structured extraction (TASK-016, FR-002).
 *
 * Text-first: the PDF's text layer is sent to Claude for extraction into
 * the zod schema. When the text layer is sparse (scanned/image-only), the
 * raw PDF is sent as a document block instead so Claude reads the page
 * images directly (PRD § Open Questions: vision fallback).
 *
 * Low confidence is an explicit state, never a silent guess: the final
 * confidence is the minimum of Claude's self-assessment and a structural
 * completeness score over the fields the verification engine depends on.
 */

/** Below this, results carry a reduced-reliability warning (never a false verdict). */
export const LOW_CONFIDENCE_THRESHOLD = 0.6;

/** The uploaded document is not an LCA report at all (PRD § Edge Cases). */
export class NotAnLcaError extends Error {
  constructor() {
    super(
      "This does not look like an LCA report. Upload the full life cycle assessment report for your product and try again.",
    );
    this.name = "NotAnLcaError";
  }
}

/** Extraction failed for a retryable reason (model error, unparseable output). */
export class ExtractionError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "ExtractionError";
  }
}

const SYSTEM_PROMPT = `You are the extraction engine of an independent LCA (Life Cycle Assessment) verification service. Your only job is to transcribe what a product LCA report actually states into a structured object. You never evaluate, never judge, and never fill gaps.

Rules:
- Extract only values printed in the document. Never infer, estimate, or compute a value the report does not state. If a value is not stated, use null (or an empty array for lists).
- Transcribe numbers exactly as printed, converting scientific notation to decimal where needed. Keep the report's sign conventions: end-of-life credits and avoided burdens are negative.
- Climate figures are in kg CO2e per functional unit unless the report clearly states otherwise.
- lifecycleStages: map each printed stage to the closest enum value (raw_materials, processing, packaging, distribution, use_phase, end_of_life) and keep the printed label and value; use "other" when nothing fits.
- sourcePlatform: the platform or consultancy that produced the report (e.g. from "Generated by ..." footers); null if not identifiable.
- comparativeAssertion: true only if the report states it supports public comparative assertions; false if it explicitly disclaims them; null if not addressed.
- criticalReview.conducted: false when the report states no critical review was conducted; null when it says nothing about review.
- missingSections: list the standard LCA report sections you could NOT find (e.g. "goal and scope", "data quality assessment", "GHG species breakdown", "uncertainty analysis", "end-of-life detail", "LCIA method").
- isLcaReport: false when the document is not a product life cycle assessment report at all (an invoice, a marketing brochure, a novel). Still extract whatever fields you can.
- confidence: your honest assessment of extraction reliability from 0 to 1. Above 0.9 only when every core section was found and unambiguous; 0.6-0.9 when minor gaps or ambiguity exist; below 0.6 when major portions were unreadable, ambiguous, or missing. Never inflate it.`;

const KEY_FIELDS: Array<(lca: LcaExtraction) => boolean> = [
  (lca) => lca.product.name !== null,
  (lca) => lca.product.functionalUnit !== null,
  (lca) => lca.goalAndScope.systemBoundary !== null,
  (lca) => lca.impacts.climateTotalKgCo2e !== null,
  (lca) => lca.lifecycleStages.length > 0,
  (lca) => lca.ghgSpecies.length > 0 || lca.ghgTotalAllSpeciesKgCo2e !== null,
  (lca) =>
    lca.dataQuality.overallScorePercent !== null ||
    lca.dataQuality.materials.length > 0,
  (lca) => lca.endOfLife.netKgCo2e !== null || lca.endOfLife.pathways.length > 0,
];

/** Share of engine-critical fields the extraction actually found. */
export function structuralCompleteness(lca: LcaExtraction): number {
  const present = KEY_FIELDS.filter((check) => check(lca)).length;
  return present / KEY_FIELDS.length;
}

function buildUserContent(
  bytes: Uint8Array,
  pageTexts: string[],
  useVision: boolean,
): Anthropic.ContentBlockParam[] {
  const instruction =
    "Extract this LCA report into the required structure. Follow the system rules exactly.";

  if (useVision) {
    return [
      {
        type: "document",
        source: {
          type: "base64",
          media_type: "application/pdf",
          data: Buffer.from(bytes).toString("base64"),
        },
      },
      { type: "text", text: instruction },
    ];
  }

  const documentText = pageTexts
    .map((page, index) => `--- Page ${index + 1} ---\n${page}`)
    .join("\n\n");

  return [
    { type: "text", text: `${instruction}\n\n${documentText}` },
  ];
}

export async function extractLcaFromPdf(
  bytes: Uint8Array,
  options: { client?: Anthropic } = {},
): Promise<ExtractionPayload> {
  // May throw PdfParseError with a plain-English reason (TASK-015/021).
  const pdfText = await extractPdfText(bytes);

  const client = options.client ?? getAnthropicClient();

  const response = await client.messages.parse({
    model: EXTRACTION_MODEL,
    max_tokens: 16000,
    thinking: { type: "adaptive" },
    system: [
      {
        type: "text",
        text: SYSTEM_PROMPT,
        // Stable prefix, cached across verifications to keep per-run cost low.
        cache_control: { type: "ephemeral" },
      },
    ],
    messages: [
      {
        role: "user",
        content: buildUserContent(bytes, pdfText.pageTexts, pdfText.isTextSparse),
      },
    ],
    output_config: {
      format: zodOutputFormat(extractionPayloadSchema),
    },
  });

  if (response.stop_reason === "refusal") {
    throw new ExtractionError(
      "The extraction engine declined to process this document. Try again, or contact support if it persists.",
    );
  }

  const payload = response.parsed_output;
  if (!payload) {
    throw new ExtractionError(
      "We could not turn this PDF into structured LCA data. Try again; if it keeps failing, re-export the report from your LCA platform.",
    );
  }

  if (!payload.isLcaReport) {
    throw new NotAnLcaError();
  }

  // Never report more confidence than the extracted structure supports.
  const confidence = Math.min(
    payload.confidence,
    structuralCompleteness(payload.lca),
  );

  return { ...payload, confidence };
}
