// Generates the known-flawed LCA PDF fixtures (TASK-014).
// Run: node tests/fixtures/generate-flawed.mjs
// Each variant is a synthetic text-based LCA report with one planted error;
// everything else is internally consistent so tests isolate the planted flaw.

import { PDFDocument, StandardFonts } from "pdf-lib";
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));

const PAGE = { width: 595, height: 842, margin: 50, lineHeight: 14 };

async function buildPdf(sections) {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  let page = doc.addPage([PAGE.width, PAGE.height]);
  let y = PAGE.height - PAGE.margin;

  const newPageIfNeeded = () => {
    if (y < PAGE.margin + PAGE.lineHeight) {
      page = doc.addPage([PAGE.width, PAGE.height]);
      y = PAGE.height - PAGE.margin;
    }
  };

  for (const section of sections) {
    newPageIfNeeded();
    if (section.heading) {
      y -= 10;
      newPageIfNeeded();
      page.drawText(section.heading, {
        x: PAGE.margin,
        y,
        size: 13,
        font: bold,
      });
      y -= PAGE.lineHeight + 4;
    }
    for (const line of section.lines ?? []) {
      newPageIfNeeded();
      page.drawText(line, { x: PAGE.margin, y, size: 9, font });
      y -= PAGE.lineHeight;
    }
  }

  return doc.save();
}

// Shared, internally consistent base report content. Numbers reconcile:
// stages sum to 0.5200; species sum to 0.5200; EoL net = gross - credits.
function baseSections({ headlineKgCo2e, dataQuality, allocation }) {
  return [
    {
      heading: "Life Cycle Assessment Report",
      lines: [
        "Product: Test Botanical Drink 250ml",
        "Company: Fixture Beverages Ltd",
        "Functional unit: 1 unit of Test Botanical Drink 250ml as sold",
        "System boundary: Cradle-to-Grave",
        "Reference year: 2025    Report date: 15 May 2026    Version: 1.0",
        "Prepared in accordance with ISO 14040:2006, ISO 14044:2006 and ISO 14067:2018.",
        "Generated by: FixtureLCA Platform",
      ],
    },
    {
      heading: "1. Goal and Scope (ISO 14044 4.2)",
      lines: [
        "Intended application: quantify the product carbon footprint for sustainability disclosures.",
        "Intended audience: internal stakeholders, B2B customers, consumers.",
        "Comparative assertion: No. This study does not support public comparative assertions.",
        "Included stages: raw materials, processing, packaging, distribution, use phase, end of life.",
        "Excluded: capital goods, employee commuting.",
        "Cut-off criteria: mass <1%, energy <1%; any flow contributing >1% to any impact category",
        "is included regardless of mass or energy contribution.",
      ],
    },
    {
      heading: "2. Methodology (ISO 14044 4.3, 4.4)",
      lines: [
        "LCIA method: ReCiPe 2016 v1.1 Midpoint (H). Climate change: IPCC AR6 GWP-100 (2021):",
        "CO2 = 1, CH4 fossil = 29.8, CH4 biogenic = 27.0, N2O = 273 kg CO2e/kg.",
        "Databases: ecoinvent 3.12 (11 factors), AGRIBALYSE 3.2 (5 factors), DEFRA 2025 (4 factors).",
        `Allocation: ${allocation}`,
      ],
    },
    ...(dataQuality
      ? [
          {
            heading: "3. Data Quality Assessment (ISO 14044 4.2.3.6)",
            lines: [
              "Overall data quality: 62% (Fair), impact-weighted average of material confidence scores.",
              "Pedigree matrix scores (1 best - 5 worst): reliability 3, completeness 2, temporal 3,",
              "geographic 2, technological 2.",
              "Primary data: 0% (0 of 12 materials). Secondary data: 100% (12 materials). Proxy: 0%.",
              "Material-level quality: Apple Juice (secondary, HIGH, 85%, Kent UK);",
              "Elderflower Extract (secondary, HIGH, 85%, Surrey UK); Sugar (secondary, MEDIUM, 50%, Norfolk UK);",
              "Water (secondary, MEDIUM, 50%, Reading UK); Glass 250ml Bottle (secondary, MEDIUM, 50%, Rotherham UK);",
              "Aluminium Cap (secondary, MEDIUM, 50%, Cranleigh UK); Label (secondary, MEDIUM, 50%, Hungerford UK).",
            ],
          },
        ]
      : []),
    {
      heading: "4. Climate Impact",
      lines: [
        `Total climate impact (GWP-100): ${headlineKgCo2e} kg CO2e per functional unit.`,
        "Lifecycle stage breakdown (kg CO2e):",
        "  Raw Materials      0.1800   (34.6%)",
        "  Processing         0.0600   (11.5%)",
        "  Packaging          0.2600   (50.0%)",
        "  Distribution       0.0300   (5.8%)",
        "  Use Phase          0.0100   (1.9%)",
        "  End of Life       -0.0200   (-3.8%)",
        "Stage total: 0.5200 kg CO2e.",
        "Scope split: Scope 1 0%, Scope 2 0%, Scope 3 100% (contract manufacture).",
      ],
    },
    {
      heading: "5. Detailed GHG Reporting (ISO 14067 6.4.9.3)",
      lines: [
        "GHG species breakdown (mass kg, CO2e kg, GWP-100):",
        "  CO2 (fossil)     0.4400   0.4400   1",
        "  CO2 (biogenic)   0.0600   0.0600   1",
        "  CO2 (LULUC)      0.0000   0.0000   1",
        "  CH4 (fossil)     0.0005   0.0149   29.8",
        "  CH4 (biogenic)   0.0000   0.0000   27.0",
        "  N2O              0.0000186 0.0051  273",
        "Total GWP-100 (all species): 0.5200 kg CO2e.",
        "Fossil carbon footprint (excl. biogenic): 0.4600 kg CO2e.",
        "Biogenic CO2 is reported separately from fossil CO2 per ISO 14067:2018 6.4.9.3.",
      ],
    },
    {
      heading: "6. End of Life",
      lines: [
        "Gross EoL emissions: 0.0300 kg CO2e. Recycling credits (avoided burden): -0.0500 kg CO2e.",
        "Net EoL impact: -0.0200 kg CO2e.",
        "Disposal pathways: Glass 250ml Bottle (74% recycling, 8% landfill, 18% incineration);",
        "Aluminium Cap (72% recycling, 8% landfill, 20% incineration);",
        "Label (74% recycling, 5% landfill, 15% incineration, 4% composting, 2% AD).",
      ],
    },
    {
      heading: "7. Interpretation, Uncertainty and Review (ISO 14044 4.5, 6)",
      lines: [
        "Significant issues: packaging dominates the footprint (50.0%); glass bottle is the largest",
        "single contributor.",
        "Uncertainty: propagated uncertainty +/-24% (95% CI, 0.395 - 0.645 kg CO2e), root-sum-of-squares",
        "with pedigree-derived GSDs. Sensitivity: +/-20% variation on top 3 contributors changes the",
        "total by up to +/-9%.",
        "Critical review: NOT CONDUCTED. A critical review per ISO 14044 Clause 6 is recommended",
        "before public comparative assertions.",
        "Recommendations: collect primary data for the glass bottle; verify transport distances.",
      ],
    },
  ];
}

const variants = [
  {
    // Planted error: GHG species total and stage totals reconcile to 0.5200,
    // but the headline claims 0.6100 (~17% off, far beyond the 2% tolerance).
    file: "flawed-ghg-mismatch.pdf",
    sections: baseSections({
      headlineKgCo2e: "0.6100",
      dataQuality: true,
      allocation:
        "Physical allocation by mass for all co-products per ISO 14044 Clause 4.3.4; no economic allocation applied.",
    }),
  },
  {
    // Planted error: the data quality section (ISO 14044 4.2.3.6) is absent.
    file: "flawed-missing-data-quality.pdf",
    sections: baseSections({
      headlineKgCo2e: "0.5200",
      dataQuality: false,
      allocation:
        "Physical allocation by mass for all co-products per ISO 14044 Clause 4.3.4; no economic allocation applied.",
    }),
  },
  {
    // Planted error: economic allocation chosen with physical allocation
    // feasible and no justification (violates the ISO 14044 4.3.4 hierarchy).
    file: "flawed-wrong-allocation.pdf",
    sections: baseSections({
      headlineKgCo2e: "0.5200",
      dataQuality: true,
      allocation:
        "Economic allocation (market price) applied to all co-products. Physical allocation was feasible but not used; no justification for departing from the ISO 14044 Clause 4.3.4 hierarchy is provided.",
    }),
  },
];

for (const variant of variants) {
  const bytes = await buildPdf(variant.sections);
  writeFileSync(path.join(here, variant.file), bytes);
  console.log(`wrote ${variant.file} (${bytes.length} bytes)`);
}
